platform :ios, '8.0'
target 'SuperHomeDemo' do
    pod 'SDWebImage'
    pod 'SDCycleScrollView'
    pod 'SDAutoLayout'
    pod 'IQKeyboardManager'
    pod 'MBProgressHUD'
    pod 'MJRefresh'
    pod 'FMDB'
    pod 'WRNavigationBar','~>1.0.9’
    pod 'AFNetworking', '~> 3.1.0'
    pod 'MMScan', '~> 0.0'# 扫一扫
    pod 'PPBadgeView'#未读个数提示
    pod 'AMap3DMap' #2D地图SDK
    pod 'AMapSearch'
    pod 'AMapLocation'
end
